# -*- coding: utf-8 -*-
"""POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2-S2jjBXGZjgmb_vPBHm4P2DB_OBaTq

Programação Orientada a Objetos (POO): Organiza o código em "objetos" que modelam dados (atributos) e comportamentos (métodos) do mundo real, utilizando classes como moldes.
"""

class Casa: # Classe
  def __init__(self, cor, quarto, banheiro): # Construtor
    self.cor = cor
    self.quarto = quarto
    self.banheiro = banheiro


  def mostrar_cor(self): # Métodos
    print(f'A cor da casa é {self.cor}')

  def mostrar_quarto(self):
    print(f'Esta casa tem {self.quarto}')

  def mostrar_banheiro(self):
    print(f'Possue {self.banheiro} banheiro(s)')

  def adicionar_quarto(self):
    self.quarto += 1
    print(f'Agora essa casa tem {self.quarto} quartos.')

  def pintar_casa(self, nova_cor):
    print(f'Pintando a casa de {self.cor} para {nova_cor}')

casa1 = Casa('Azul', 5, 2) # Instâncias
casa2 = Casa('Amarela', 3, 1)

print('\nCasa 1: ')
casa1.mostrar_cor()
casa1.mostrar_quarto()
casa1.mostrar_banheiro()
casa1.adicionar_quarto()
casa1.pintar_casa('Verde')

print('\nCasa 2: ')
casa2.mostrar_cor()
casa2.mostrar_quarto()
casa2.mostrar_banheiro()
casa2.adicionar_quarto()
casa2.pintar_casa('Vermelho')